export const SELECTED_IMAGE = 'SELECTED_IMAGE';

export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_FAILURE = 'SEARCH_MEDIA_FAILURE';

export const GET_IMAGE_DETAILS_REQUEST = 'GET_IMAGE_DETAILS_REQUEST';
export const GET_IMAGE_DETAILS_SUCCESS = 'GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_FAILURE = 'GET_IMAGE_DETAILS_FAILURE';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CHECK_STATUS_REQUEST = 'CHECK_STATUS_REQUEST';
export const CHECK_STATUS_SUCCESS = 'CHECK_STATUS_SUCCESS';
export const CHECK_STATUS_FAILURE = 'CHECK_STATUS_FAILURE';

export const GET_AGGREGATION_REQUEST = 'GET_AGGREGATION_REQUEST';
export const GET_AGGREGATION_SUCCESS = 'GET_AGGREGATION_SUCCESS';
export const GET_AGGREGATION_FAILURE = 'GET_AGGREGATION_FAILURE';
