export const SELECTED_IMAGE = 'SELECTED_IMAGE';

export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_FAILURE = 'SEARCH_MEDIA_FAILURE';

export const GET_IMAGE_DETAILS_REQUEST = 'GET_IMAGE_DETAILS_REQUEST';
export const GET_IMAGE_DETAILS_SUCCESS = 'GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_FAILURE = 'GET_IMAGE_DETAILS_FAILURE';

// Events

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const SAVE_EVENTS_REQUEST = 'SAVE_EVENTS_REQUEST';
export const SAVE_EVENTS_SUCCESS = 'SAVE_EVENTS_SUCCESS';
export const SAVE_EVENTS_FAILURE = 'SAVE_EVENTS_FAILURE';

// Event

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

export const REMOVE_EVENT_REQUEST = 'REMOVE_EVENT_REQUEST';
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS';
export const REMOVE_EVENT_FAILURE = 'REMOVE_EVENT_FAILURE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const INCVIEW_EVENT_REQUEST = 'INCVIEW_EVENT_REQUEST';
export const INCVIEW_EVENT_SUCCESS = 'INCVIEW_EVENT_SUCCESS';
export const INCVIEW_EVENT_FAILURE = 'INCVIEW_EVENT_FAILURE';

export const SYNC_EVENT_REQUEST = 'SYNC_EVENT_REQUEST';
export const SYNC_EVENT_SUCCESS = 'SYNC_EVENT_SUCCESS';
export const SYNC_EVENT_FAILURE = 'SYNC_EVENT_FAILURE';

// Most viewed events

export const GET_MOSTVIEWEDEVENTS_REQUEST = 'GET_MOSTVIEWEDEVENTS_REQUEST';
export const GET_MOSTVIEWEDEVENTS_SUCCESS = 'GET_MOSTVIEWEDEVENTS_SUCCESS';
export const GET_MOSTVIEWEDEVENTS_FAILURE = 'GET_MOSTVIEWEDEVENTS_FAILURE';

// Film events

export const GET_FILM_REQUEST = 'GET_FILM_REQUEST';
export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS';
export const GET_FILM_FAILURE = 'GET_FILM_FAILURE';

// Child events

export const GET_CHILD_REQUEST = 'GET_CHILD_REQUEST';
export const GET_CHILD_SUCCESS = 'GET_CHILD_SUCCESS';
export const GET_CHILD_FAILURE = 'GET_CHILD_FAILURE';

// Promo events

export const GET_PROMO_REQUEST = 'GET_PROMO_REQUEST';
export const GET_PROMO_SUCCESS = 'GET_PROMO_SUCCESS';
export const GET_PROMO_FAILURE = 'GET_PROMO_FAILURE';

// Attention events

export const GET_ATTENTION_REQUEST = 'GET_ATTENTION_REQUEST';
export const GET_ATTENTION_SUCCESS = 'GET_ATTENTION_SUCCESS';
export const GET_ATTENTION_FAILURE = 'GET_ATTENTION_FAILURE';

// Categories

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

// Users

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// Pages

export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAILURE = 'GET_PAGES_FAILURE';

// Authors

export const GET_AUTHORS_REQUEST = 'GET_AUTHORS_REQUEST';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_FAILURE = 'GET_AUTHORS_FAILURE';

// Login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Logout

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CHECK_STATUS_REQUEST = 'CHECK_STATUS_REQUEST';
export const CHECK_STATUS_SUCCESS = 'CHECK_STATUS_SUCCESS';
export const CHECK_STATUS_FAILURE = 'CHECK_STATUS_FAILURE';

// Aggregation

export const GET_AGGREGATION_REQUEST = 'GET_AGGREGATION_REQUEST';
export const GET_AGGREGATION_SUCCESS = 'GET_AGGREGATION_SUCCESS';
export const GET_AGGREGATION_FAILURE = 'GET_AGGREGATION_FAILURE';

export const TOGGLE_VALID = 'TOGGLE_VALID';
export const TOGGLE_HIDDEN = 'TOGGLE_HIDDEN';
export const TOGGLE_INTEGRATE = 'TOGGLE_INTEGRATE';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_PHONE = 'SET_PHONE';
export const SET_TICKET_URL = 'SET_TICKET_URL';
