export const SELECTED_IMAGE = 'SELECTED_IMAGE';

export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_FAILURE = 'SEARCH_MEDIA_FAILURE';

export const GET_IMAGE_DETAILS_REQUEST = 'GET_IMAGE_DETAILS_REQUEST';
export const GET_IMAGE_DETAILS_SUCCESS = 'GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_FAILURE = 'GET_IMAGE_DETAILS_FAILURE';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const SEARCH_MEDIA_REQUEST2 = 'SEARCH_MEDIA_REQUEST2';
export const SEARCH_MEDIA_SUCCESS2 = 'SEARCH_MEDIA_SUCCESS2';
export const SEARCH_MEDIA_FAILURE2 = 'SEARCH_MEDIA_FAILURE2';
